webapp:
  ip: 0.0.0.0
  port: 5010
  ssh_cert: adhoc

llm: 
  type: LangChainChatOpenAI
  model_name: gpt-4o-mini
  api_key: $ENV{OPENAI_API_KEY}
  temperature: 0  
  seed: 42

messages:
  type: LangChainPrompts
  json_convert: true
  memory_key: chat_history

memory:
  personal:
    type: LangChainBuffer
    memory_key: chat_history
    return_messages: true
  project:
    type: LangChainSummary
    memory_key: chat_history
    return_messages: true
    llm_model:
      type: LangChainChatOpenAI
      model_name: gpt-4o-mini
      api_key: $ENV{OPENAI_API_KEY}
      temperature: 0  
      seed: 42
    buffer: $PROMPT{project_info}

prompts:
  type: JinjaTemplate
  environment: examples/app_memory/prompts/
  templates:
    project_info: project_info.txt
    select_memory: select_memory.txt

logger:
  name: MEMAPP
  log_file: examples/app_memory/logs/memapp.log
  level: DEBUG