webapp:
  ip: 0.0.0.0
  port: 5010
  ssh_cert: adhoc

llm: 
  type: LangChainChatOpenAI
  model_name: gpt-4o-mini
  api_key: $ENV{OPENAI_API_KEY}
  temperature: 0  
  seed: 42

messages:
  type: LangChainPrompts
  json_convert: true
  memory_key: chat_history

memories:
  messages:
    type: LangChainBufferWindow
    memory_key: chat_history
    window: 10
    return_messages: true
  core:
    type: ChromaCollection
    path: examples/app_memory/data
    collection: CoreMemGpt
    reset: true
  recall:
    type: ChromaCollection
    path: examples/app_memory/data
    collection: RecallMemGpt
    reset: true
  loader:
    type: ChromaForSentences
  retriever:  
    type: ChromaForSentences
    expansion_type: None
    n_results: 3

prompts:
  type: JinjaTemplate
  environment: examples/app_memory/prompts/
  templates:
    project_info: project_info.txt
    load_memory: load_memory.txt
    store_memory: store_memory.txt

logger:
  name: MEMAPP
  log_file: examples/app_memory/logs/memapp.log
  level: DEBUG