webapp:
  ip: 0.0.0.0
  port: 5001
  brand: hpe
  # ssh_cert:
  #   certfile: "/path/to/cert.pem"
  #   keyfile: "/path/to/key.pem"
  llm_endpoint:
    endpoint_prefix: "/v1"
    available_models: []

chat:
  type: LangChainAgentExecutor
  system_prompt: $PROMPT{chat_system_prompt}
  model: 
    type: LangChainChatOpenAI
    model_name: gpt-4o
    api_key: $ENV{OPENAI_API_KEY}
    temperature: 0
    seed: 42
  memory:
    type: LangChainBuffer
    memory_key: chat_history
    return_messages: true
  tools:
    type: LangChainStructured
  discovery:
    timeout: 100
    cert_verify: false
  verbose: true
  stateless: true

projects:
  - name: "Personal Chat"
    memory:
      type: LangChainBuffer
      memory_key: chat_history
      return_messages: true
    tools:
      - "mcp://chat"                  # ChatService via MCP
      # - "https://127.0.0.1:5002/"   # ChatService (URL discovery fallback)
  - name: "Project 5G Network"
    memory:
      type: LangChainRemote
      memory_key: chat_history
      return_messages: true
      base_url: "https://127.0.0.1:5010/"
      timeout: 100
      cert_verify: false
    tools:
      - "mcp://tool_agents"           # OpenAPIManager via MCP
      - "mcp://rag"                   # RagService via MCP
      # - "https://127.0.0.1:5005/"   # OpenAPIManager (URL discovery fallback)
      # - "https://127.0.0.1:5003/"   # RagService (URL discovery fallback)
  - name: "Project Meteo"
    memory:
      type: LangChainBuffer
      memory_key: chat_history
      return_messages: true
    tools:
      - "mcp://tool_api"              # TemperatureFinder via MCP
      - "mcp://tool_analyzer"         # TemperatureAnalyzer via MCP
      # - "https://127.0.0.1:5006/"   # TemperatureFinder (URL discovery fallback)
      # - "https://127.0.0.1:5004/"   # TemperatureAnalyzer (URL discovery fallback)

prompts:
  type: JinjaTemplate
  environment: src/platform/orchestrator/prompts/
  templates:
    chat_system_prompt: chat_system_prompt.txt

logger:
  name: ATHON
  log_file: src/platform/orchestrator/logs/athon.log
  level: DEBUG