classDiagram
  class AgentState {
  }
  class AgentTool {
  }
  class Argument {
  }
  class AthonTool {
  }
  class BaseChatMemory {
  }
  class BaseChatModel {
  }
  class BaseDataExtractor {
  }
  class BaseDataLoader {
  }
  class BaseDataRetriever {
  }
  class BaseDataStorage {
  }
  class BaseDataTransformer {
  }
  class BaseGame {
  }
  class BaseMessageManager {
  }
  class BasePromptRender {
  }
  class BaseReasoningEngine {
  }
  class BaseTaskForce {
  }
  class BaseToolRepository {
  }
  class ChatMemory {
  }
  class ChatModel {
  }
  class ChromaCollectionDataStorage {
  }
  class ChromaForSentenceDataLoader {
  }
  class ChromaForSentenceDataRetriever {
  }
  class Config {
  }
  class Config {
  }
  class Config {
  }
  class Config {
  }
  class Config {
  }
  class Config {
  }
  class Config {
  }
  class Config {
  }
  class Config {
  }
  class Config {
  }
  class Config {
  }
  class Config {
  }
  class Config {
  }
  class Config {
  }
  class Config {
  }
  class Config {
  }
  class Config {
  }
  class Config {
  }
  class Config {
  }
  class Config {
  }
  class Config {
  }
  class Config {
  }
  class Config {
  }
  class Config {
  }
  class Config {
  }
  class Config {
  }
  class Config {
  }
  class Config {
  }
  class Config {
  }
  class Config {
  }
  class Config {
  }
  class Config {
  }
  class Config {
  }
  class Config {
  }
  class Config {
  }
  class Config {
  }
  class Config {
  }
  class Config {
  }
  class Config {
  }
  class Config {
  }
  class Config {
  }
  class Config {
  }
  class Config {
  }
  class Config {
  }
  class ConfigAgent {
  }
  class ConfigAgent {
  }
  class ConfigAgent {
  }
  class ConfigClean {
  }
  class ConfigClean {
  }
  class ConfigEdges {
  }
  class ConfigEnrich {
  }
  class ConfigTask {
  }
  class ConfigTask {
  }
  class ConfigTask {
  }
  class ConfigTransform {
  }
  class ConfigTransform {
  }
  class CrewAIMultiAgentTaskForce {
  }
  class CteActionRunnerDataTransformer {
  }
  class CustomLangChainRemoteMemory {
  }
  class CustomVectorStoreRetrieverMemory {
  }
  class DataExtractor {
  }
  class DataLoader {
  }
  class DataRetriever {
  }
  class DataStorage {
  }
  class DataTransformer {
  }
  class FantasiaGenesis {
  }
  class FileCache {
  }
  class Game {
  }
  class GetHero {
  }
  class GetRules {
  }
  class GetToolInput {
  }
  class GetWorld {
  }
  class Interface {
  }
  class InterfaceField {
  }
  class JinjaTemplatePromptRender {
  }
  class LangChainAgentExecutor {
  }
  class LangChainAzureChatOpenAIModel {
  }
  class LangChainBufferMemory {
  }
  class LangChainBufferWindowMemory {
  }
  class LangChainChatAnthropicModel {
  }
  class LangChainChatGoogleGenAIModel {
  }
  class LangChainChatMistralAIModel {
  }
  class LangChainChatNvidiaModel {
  }
  class LangChainChatOpenAIModel {
  }
  class LangChainChatVLLMModel {
  }
  class LangChainChromaStoreMemory {
  }
  class LangChainPromptsMessageManager {
  }
  class LangChainRemoteMemory {
  }
  class LangChainStructuredToolRepository {
  }
  class LangChainSummaryMemory {
  }
  class LangGraphAgentTaskForce {
  }
  class LlamaIndexBufferMemory {
  }
  class LlamaIndexOpenAIModel {
  }
  class LlamaIndexReActEngine {
  }
  class Logger {
  }
  class LoggerSingleton {
  }
  class Manifest {
  }
  class MarkitdownForSectionsDataExtractor {
  }
  class MessageManager {
  }
  class MilvusCollectionDataStorage {
  }
  class MilvusForSentenceDataLoader {
  }
  class MilvusForSentenceDataRetriever {
  }
  class OpenApiManager {
  }
  class OpenApiManagerTool {
  }
  class OpenApiManagerToolInput {
  }
  class PandasReadExcelExtractor {
  }
  class PlayLottery {
  }
  class PlayToolInput {
  }
  class PromptRender {
  }
  class ChatTool {
  }
  class PyMuPdfForSectionsDataExtractor {
  }
  class QdrantCollectionDataStorage {
  }
  class QdrantForSentenceDataLoader {
  }
  class QdrantForSentenceDataRetriever {
  }
  class RagTool {
  }
  class ReasoningEngine {
  }
  class Result {
  }
  class Result {
  }
  class Result {
  }
  class Result {
  }
  class Result {
  }
  class Result {
  }
  class Result {
  }
  class Result {
  }
  class Result {
  }
  class Result {
  }
  class Result {
  }
  class Result {
  }
  class Result {
  }
  class Result {
  }
  class Result {
  }
  class Result {
  }
  class SaveHero {
  }
  class SaveToolInput {
  }
  class SaveWorld {
  }
  class TaskForce {
  }
  class TemplateEngine {
  }
  class ToolDiscovery {
  }
  class ToolManager {
  }
  class ToolRepository {
  }
  class UnstructuredSectionsDataExtractor {
  }
  class WhoAmI {
  }
  LangChainAgentExecutor --|> BaseReasoningEngine
  LlamaIndexReActEngine --|> BaseReasoningEngine
  CrewAIMultiAgentTaskForce --|> BaseTaskForce
  Config --|> Config
  ConfigAgent --|> ConfigAgent
  ConfigTask --|> ConfigTask
  LangGraphAgentTaskForce --|> BaseTaskForce
  Config --|> Config
  ConfigAgent --|> ConfigAgent
  ConfigTask --|> ConfigTask
  LangChainStructuredToolRepository --|> BaseToolRepository
  LangChainBufferMemory --|> BaseChatMemory
  Config --|> Config
  LangChainBufferWindowMemory --|> BaseChatMemory
  Config --|> Config
  LangChainChromaStoreMemory --|> BaseChatMemory
  Config --|> Config
  LangChainRemoteMemory --|> BaseChatMemory
  Config --|> Config
  LangChainSummaryMemory --|> BaseChatMemory
  Config --|> Config
  LlamaIndexBufferMemory --|> BaseChatMemory
  Config --|> Config
  LangChainPromptsMessageManager --|> BaseMessageManager
  LangChainAzureChatOpenAIModel --|> BaseChatModel
  Config --|> Config
  LangChainChatAnthropicModel --|> BaseChatModel
  Config --|> Config
  LangChainChatGoogleGenAIModel --|> BaseChatModel
  Config --|> Config
  LangChainChatMistralAIModel --|> BaseChatModel
  Config --|> Config
  LangChainChatNvidiaModel --|> BaseChatModel
  LangChainChatOpenAIModel --|> BaseChatModel
  Config --|> Config
  LangChainChatVLLMModel --|> BaseChatModel
  Config --|> Config
  LlamaIndexOpenAIModel --|> BaseChatModel
  Config --|> Config
  JinjaTemplatePromptRender --|> BasePromptRender
  MarkitdownForSectionsDataExtractor --|> BaseDataExtractor
  PandasReadExcelExtractor --|> BaseDataExtractor
  Config --|> Config
  PyMuPdfForSectionsDataExtractor --|> BaseDataExtractor
  Config --|> Config
  UnstructuredSectionsDataExtractor --|> BaseDataExtractor
  Config --|> Config
  ChromaForSentenceDataLoader --|> BaseDataLoader
  MilvusForSentenceDataLoader --|> BaseDataLoader
  QdrantForSentenceDataLoader --|> BaseDataLoader
  ChromaForSentenceDataRetriever --|> BaseDataRetriever
  Config --|> Config
  Result --|> Result
  MilvusForSentenceDataRetriever --|> BaseDataRetriever
  Config --|> Config
  Result --|> Result
  QdrantForSentenceDataRetriever --|> BaseDataRetriever
  Config --|> Config
  Result --|> Result
  ChromaCollectionDataStorage --|> BaseDataStorage
  Config --|> Config
  MilvusCollectionDataStorage --|> BaseDataStorage
  Config --|> Config
  QdrantCollectionDataStorage --|> BaseDataStorage
  Config --|> Config
  CteActionRunnerDataTransformer --|> BaseDataTransformer
  Config --|> Config
  ConfigClean --|> ConfigClean
  ConfigTransform --|> ConfigTransform
  AgentTool --|> ToolManager
  ChatTool --|> ToolManager
  RagTool --|> ToolManager
  FantasiaGenesis --|> BaseGame
  WhoAmI --|> BaseGame
  FileCache --* MarkitdownForSectionsDataExtractor : file_cache
  FileCache --* PandasReadExcelExtractor : file_cache
  FileCache --* PyMuPdfForSectionsDataExtractor : file_cache
  FileCache --* UnstructuredSectionsDataExtractor : file_cache
  Config --* FileCache : config
  Config --* Logger : config
  Config --* Logger : config
  Config --* LangChainAgentExecutor : config
  Config --* LlamaIndexReActEngine : config
  Result --* LangChainAgentExecutor : result
  Result --* LlamaIndexReActEngine : result
  Result --* CrewAIMultiAgentTaskForce : result
  Result --* LangGraphAgentTaskForce : result
  Config --* CrewAIMultiAgentTaskForce : config
  Config --* LangGraphAgentTaskForce : config
  Result --* LangChainStructuredToolRepository : result
  Result --* LangChainBufferMemory : result
  Result --* LangChainBufferWindowMemory : result
  Result --* LangChainChromaStoreMemory : result
  Result --* LangChainRemoteMemory : result
  Result --* LangChainSummaryMemory : result
  Result --* LlamaIndexBufferMemory : result
  Config --* LangChainBufferMemory : config
  Config --* LangChainBufferWindowMemory : config
  CustomVectorStoreRetrieverMemory --* Result : memory
  CustomVectorStoreRetrieverMemory --* LangChainChromaStoreMemory : memory
  Config --* LangChainChromaStoreMemory : config
  CustomLangChainRemoteMemory --* Result : memory
  CustomLangChainRemoteMemory --* LangChainRemoteMemory : memory
  Config --* LangChainRemoteMemory : config
  Config --* LangChainSummaryMemory : config
  Config --* LlamaIndexBufferMemory : config
  Config --* LangChainPromptsMessageManager : config
  Result --* LangChainPromptsMessageManager : result
  Config --* LangChainChatNvidiaModel : config
  Result --* LangChainAzureChatOpenAIModel : result
  Result --* LangChainChatAnthropicModel : result
  Result --* LangChainChatGoogleGenAIModel : result
  Result --* LangChainChatMistralAIModel : result
  Result --* LangChainChatNvidiaModel : result
  Result --* LangChainChatOpenAIModel : result
  Result --* LangChainChatVLLMModel : result
  Result --* LlamaIndexOpenAIModel : result
  Config --* LangChainAzureChatOpenAIModel : config
  Config --* LangChainChatAnthropicModel : config
  Config --* LangChainChatGoogleGenAIModel : config
  Config --* LangChainChatMistralAIModel : config
  Config --* LangChainChatOpenAIModel : config
  Config --* LangChainChatVLLMModel : config
  Config --* LlamaIndexOpenAIModel : config
  Config --* JinjaTemplatePromptRender : config
  Result --* JinjaTemplatePromptRender : result
  Config --* MarkitdownForSectionsDataExtractor : config
  Result --* MarkitdownForSectionsDataExtractor : result
  Result --* PandasReadExcelExtractor : result
  Result --* PyMuPdfForSectionsDataExtractor : result
  Result --* UnstructuredSectionsDataExtractor : result
  Config --* PandasReadExcelExtractor : config
  Config --* PyMuPdfForSectionsDataExtractor : config
  Config --* UnstructuredSectionsDataExtractor : config
  Config --* ChromaForSentenceDataLoader : config
  Config --* MilvusForSentenceDataLoader : config
  Config --* QdrantForSentenceDataLoader : config
  Result --* ChromaForSentenceDataLoader : result
  Result --* MilvusForSentenceDataLoader : result
  Result --* QdrantForSentenceDataLoader : result
  Config --* ChromaForSentenceDataRetriever : config
  Result --* ChromaForSentenceDataRetriever : result
  Config --* MilvusForSentenceDataRetriever : config
  Result --* MilvusForSentenceDataRetriever : result
  Config --* QdrantForSentenceDataRetriever : config
  Result --* QdrantForSentenceDataRetriever : result
  Result --* ChromaCollectionDataStorage : result
  Result --* MilvusCollectionDataStorage : result
  Result --* QdrantCollectionDataStorage : result
  Config --* ChromaCollectionDataStorage : config
  Config --* MilvusCollectionDataStorage : config
  Config --* QdrantCollectionDataStorage : config
  ConfigEnrich --* Config : enrich
  Result --* CteActionRunnerDataTransformer : result
  Config --* CteActionRunnerDataTransformer : config
  ConfigClean --* Config : clean
  ConfigTransform --* Config : transform
  Config --* ToolDiscovery : config
  Config --* FantasiaGenesis : config
  Config --* WhoAmI : config
  Result --* FantasiaGenesis : result
  Result --* WhoAmI : result
