webapp:
  ip: 0.0.0.0
  port: 5005
  ssh_cert: adhoc

tool:
  name: TemperatureAnalyzer
  function: $FUNCTION{temperature_analyzer}
  arguments:
    - name: query
      type: str
      description: $PROMPT{field_query_description}
      default : null    
  description: $PROMPT{tool_description}
  return_direct: true

function:
  plot_function: _create_plot
  file_path: src/examples/tool_analyzer/data/
  file_name: GlobalLandTemperaturesByCountry.csv
  chunksize: 10000
  llm:
    type: LangChainChatOpenAI
    model_name: gpt-4o
    api_key: $ENV{OPENAI_API_KEY}
    temperature: 0  
    seed: 42

prompts:
  type: JinjaTemplate
  environment: src/examples/tool_analyzer/prompts/
  templates:
    tool_description: tool_description.txt
    field_query_description: field_query_description.txt
    system_prompt: system_prompt.txt
    analysis_request: analysis_request.txt
     
logger:
  name: TEMPERATURE_ANALYZER
  log_file: src/examples/tool_analyzer/logs/temperature_analyzer.log
  level: DEBUG