name: Python Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PYTHON_VERSION: "3.11.9"
  OPENAI_API_KEY: "test_api_key"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils tesseract-ocr libtesseract-dev libmagic-dev
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
        
      - name: Ensure Python version
        run: uv python install ${{ env.PYTHON_VERSION }}

      - name: Run tests
        run: uv run --python ${{ env.PYTHON_VERSION }} --with-editable ".[all,test]" pytest --maxfail=10 --disable-warnings -v \
          --deselect=tests/lib/services/agents/test_agents_integration.py \
          --deselect=tests/lib/services/chat/test_chat_integration.py \
          --deselect=tests/lib/services/rag/test_rag_integration.py \
